# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b13732e1b63ef1efcc4cdc116c4d4bde7e1eff0d24cbe09849493fd8f7c88dc5a41b5e7ac5c19796b5007167b8c40964f25b46569e92ca24d24d1ecf10ec9d41

test:
  secret_key_base: 187e83170d5d1c1dd52148c5d5b882b150da9674cce3d20e0eb103ee00d139b2bd255c25477d83260b9c6e0e35dffc4c0ef22659656695c5e3db8dddb49df8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
